### ISSUE TITLE
Adding some characters

### ISSUE THREAD

**Issue by mantvius** [LenShustek/fix_UTF8#1]
Could you please add these characters to your tool?
https://docs.google.com/spreadsheets/d/18g1LSe63F5zw2Y9XTfLKlud-GEIn0mMJkNW3wCso8iw/edit?usp=sharing

Thanks!

**Comment by LenShustek** [comment]
Unfortunately if I were to start adding the characters for all the foreign languages, and other special symbols, the translation file would be thousands of lines long. I think it's best to let people make their own additions to their translations.txt file to add the translations that matter to them.
